### ISSUE TITLE
Deno Lib  does not follow established practices on deno.land/x

### ISSUE THREAD

**Issue by bjesuiter** [axiomhq/axiom-deno#1]
Hi there! 

First, I'm happy that axiom has a small deno client, since I love deno and appreciate the recognition! 
I have some improvement suggestions to make, so that this lib better fits into the existing ecosystem. 

(Note: A PR is already in the works, but I want to document my intentions somewhere) 

## 1. No mod.ts file available
I was confused, why there is no mod.ts file at: `https://deno.land/x/axiom@v0.1.0alpha6/mod.ts`. This is an established convention now. I for myself find it a little annoying, but the community developed into that direction, so I think, this lib should follow for consistency. 

## 2. The lib code wants more permissions than it needs

The line 

```
const env = Deno.env.toObject();
```

results in deno requesting permission to read ALL env vars: 

<img width="767" alt="Bildschirm­foto 2023-03-05 um 14 21 20" src="https://user-images.githubusercontent.com/2365676/222963064-bc9c4388-ebdd-466b-8608-1cc8c0744285.png">

Since in deno there is this security concept, libraries should embrace it by only requesting permissions to what they really need. 
This can be done by only accessing the env vars, which are needed, like so: `Deno.env.get("MY_ENV_VAR")`

## 3. Examples should be in TS 

I think it does not make sense for a deno lib to have examples in js, especially since deno has first class ts support!

**Comment by ImLunaHey** [comment]
Can this issue be closed now?

**Comment by lukasmalkmus** [comment]
@bahlo merged the PR, so yeah :)
